---
- name: Deploy Weather-site to Apache on web servers
  hosts: webservers
  become: yes

  vars:
    # Change this if your default branch is "master"
    repo_branch: "main"

    # Public URL by default; Jenkins can override with a tokenized URL via --extra-vars
    repo_url: "https://github.com/Krish-venom/Weather-site.git"

    web_root: "/var/www/html"
    set_owner: true

  pre_tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: yes
        cache_valid_time: 3600

  tasks:
    - name: Install Apache
      ansible.builtin.apt:
        name: apache2
        state: present

    - name: Ensure Apache is enabled and running
      ansible.builtin.service:
        name: apache2
        state: started
        enabled: yes

    - name: Ensure web root exists
      ansible.builtin.file:
        path: "{{ web_root }}"
        state: directory
        owner: www-data
        group: www-data
        mode: "0755"

    - name: Deploy site by cloning from GitHub (idempotent)
      ansible.builtin.git:
        repo: "{{ repo_url }}"
        dest: "{{ web_root }}"
        version: "{{ repo_branch }}"
        force: yes
        update: yes
      notify: Restart Apache

    - name: Ensure correct ownership on deployed files
      ansible.builtin.file:
        path: "{{ web_root }}"
        state: directory
        recurse: yes
        owner: "{{ 'www-data' if set_owner else omit }}"
        group: "{{ 'www-data' if set_owner else omit }}"

    - name: Allow HTTP in UFW if present (non-fatal)
      ansible.builtin.command: ufw allow 80/tcp
      changed_when: false
      ignore_errors: yes

  handlers:
    - name: Restart Apache
      ansible.builtin.service:
        name: apache2
        state: restarted
